// <auto-generated />
using System;
using MenuApp.OrderService.EntityFramework.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MenuApp.OrderService.EntityFramework.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210511120510_AddSessions")]
    partial class AddSessions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("MenuApp.OrderService.Logic.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("MenuItemId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("MenuApp.OrderService.Logic.Entities.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("MenuItem");
                });

            modelBuilder.Entity("MenuApp.OrderService.Logic.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MenuApp.OrderService.Logic.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("MenuApp.OrderService.Logic.Entities.Ingredient", b =>
                {
                    b.HasOne("MenuApp.OrderService.Logic.Entities.MenuItem", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("MenuItemId");
                });

            modelBuilder.Entity("MenuApp.OrderService.Logic.Entities.MenuItem", b =>
                {
                    b.HasOne("MenuApp.OrderService.Logic.Entities.Order", null)
                        .WithMany("OrderList")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("MenuApp.OrderService.Logic.Entities.Order", b =>
                {
                    b.HasOne("MenuApp.OrderService.Logic.Entities.Session", null)
                        .WithMany("Orders")
                        .HasForeignKey("SessionId");
                });

            modelBuilder.Entity("MenuApp.OrderService.Logic.Entities.MenuItem", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("MenuApp.OrderService.Logic.Entities.Order", b =>
                {
                    b.Navigation("OrderList");
                });

            modelBuilder.Entity("MenuApp.OrderService.Logic.Entities.Session", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
