// <auto-generated />
using System;
using MenuApp.OrderService.EntityFramework.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MenuApp.OrderService.EntityFramework.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210511133126_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("MenuApp.OrderService.Logic.Entities.IngredientChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("OrderItemId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId");

                    b.ToTable("IngredientChange");
                });

            modelBuilder.Entity("MenuApp.OrderService.Logic.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MenuApp.OrderService.Logic.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<Guid>("MenuItem")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("MenuApp.OrderService.Logic.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("MenuApp.OrderService.Logic.Entities.IngredientChange", b =>
                {
                    b.HasOne("MenuApp.OrderService.Logic.Entities.OrderItem", null)
                        .WithMany("IngredientChanges")
                        .HasForeignKey("OrderItemId");
                });

            modelBuilder.Entity("MenuApp.OrderService.Logic.Entities.Order", b =>
                {
                    b.HasOne("MenuApp.OrderService.Logic.Entities.Session", null)
                        .WithMany("Orders")
                        .HasForeignKey("SessionId");
                });

            modelBuilder.Entity("MenuApp.OrderService.Logic.Entities.OrderItem", b =>
                {
                    b.HasOne("MenuApp.OrderService.Logic.Entities.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("MenuApp.OrderService.Logic.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MenuApp.OrderService.Logic.Entities.OrderItem", b =>
                {
                    b.Navigation("IngredientChanges");
                });

            modelBuilder.Entity("MenuApp.OrderService.Logic.Entities.Session", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
